//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public int CustomerID { get; set; }
        public int GoodID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string UserEmail { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Good Good { get; set; }
    }
}
